# https://goreleaser.com
project_name: sstv

# Build
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    main: ./cmd/sstv
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w
      - -X "github.com/l3uddz/sstv/build.Version={{ .Version }}"
      - -X "github.com/l3uddz/sstv/build.GitCommit={{ .ShortCommit }}"
      - -X "github.com/l3uddz/sstv/build.Timestamp={{ .Timestamp }}"
    flags:
      - -trimpath

# Archive
archives:
  -
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: "binary"

# Checksum
checksum:
  name_template: "checksums.txt"
  algorithm: sha512

# Snapshot
snapshot:
  name_template: "{{ .Major }}.{{ .Minor }}.{{ .Patch }}-dev+{{ .ShortCommit }}"

# Changelog
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge branch"